/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormFugas.java
 *
 * Created on Nov 4, 2011, 8:12:28 AM
 *
 * @author rebonatto
 */

package Visualizacao;

import Graficos.CriaGrafico;
import Uteis.Conversoes;
import Uteis.CalendarComboBox;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Formularios.BeanFuga;
import modelo.CapturaAtual;
import modelo.Equipamento;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import persistencia.CapturaAtualDAO;
import persistencia.EquipamentoDAO;

/**
 *
 * @author rebonatto
 */
public class FormComparaArquivadas extends javax.swing.JDialog {    
    private CapturaAtualDAO capdao = new CapturaAtualDAO();
    private EquipamentoDAO eqpdao = new EquipamentoDAO();   
        
    private CapturaAtual bean = new CapturaAtual();    

    Vector titulosArquivadas = new Vector();
    Vector linhasArquivadas = new Vector();
    
    /** Creates new form FormEquipamento */
    public FormComparaArquivadas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setTitle("Formulário de Ondas Arquivadas");
        
        //preenche o combobox       
        comboEquipamento.removeAllItems();                
        for (Equipamento equip : eqpdao.lista()) {
            comboEquipamento.addItem((Equipamento) equip);            
        }
        Calendar hoje = Calendar.getInstance();
        comboDataFim.setSelectedItem(Conversoes.CalendarToString(hoje));
        comboDataIni.setSelectedItem(Conversoes.CalendarToString(hoje));
        
        
        montaTabelaArquivadas() ;         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoOndas = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelOnda1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelHarmonicas1 = new javax.swing.JPanel();
        panelHarmonicas2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtEquipamento = new javax.swing.JLabel();
        jtfEquipamento = new javax.swing.JTextField();
        comboEquipamento = new javax.swing.JComboBox();
        radioData = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        comboDataIni = new CalendarComboBox();
        jLabel1 = new javax.swing.JLabel();
        comboDataFim = new CalendarComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaArquivadas = new javax.swing.JTable();
        btnCarregaOndas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelHarmonicas = new javax.swing.JPanel();
        panelOnda = new javax.swing.JPanel();
        checkEquipamentos = new javax.swing.JCheckBox();
        CheckFase = new javax.swing.JCheckBox();
        CheckFuga = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Ondas Deslocadas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, 30));

        panelOnda1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOnda1.setPreferredSize(new java.awt.Dimension(240, 220));
        jPanel2.add(panelOnda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 420, 380));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Componente DC e Harmônicas");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, -1, -1));

        panelHarmonicas1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHarmonicas1.setPreferredSize(new java.awt.Dimension(240, 220));
        jPanel2.add(panelHarmonicas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 420, 380));

        panelHarmonicas2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHarmonicas2.setPreferredSize(new java.awt.Dimension(240, 220));
        jPanel2.add(panelHarmonicas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 420, 380));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("Forma de Onda");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 30));

        jTabbedPane1.addTab("Compara", jPanel2);

        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEquipamento.setText("Equipamento:");
        txtEquipamento.setEnabled(false);
        jPanel1.add(txtEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, -1));

        jtfEquipamento.setEnabled(false);
        jtfEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEquipamentoActionPerformed(evt);
            }
        });
        jtfEquipamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEquipamentoFocusLost(evt);
            }
        });
        jPanel1.add(jtfEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 62, -1));

        comboEquipamento.setEditable(true);
        comboEquipamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEquipamento.setEnabled(false);
        comboEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEquipamentoActionPerformed(evt);
            }
        });
        jPanel1.add(comboEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 234, -1));

        radioData.setText("Selecionar Data");
        radioData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDataActionPerformed(evt);
            }
        });
        jPanel1.add(radioData, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jLabel9.setText("De:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        comboDataIni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDataIni.setEnabled(false);
        jPanel1.add(comboDataIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 124, -1));

        jLabel1.setText("Até:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, -1));

        comboDataFim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDataFim.setEnabled(false);
        jPanel1.add(comboDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 124, -1));

        tabelaArquivadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaArquivadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaArquivadasMouseClicked(evt);
            }
        });
        tabelaArquivadas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaArquivadasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaArquivadas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1220, 130));

        btnCarregaOndas.setText("Carregar Ondas");
        btnCarregaOndas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregaOndasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarregaOndas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, 30));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Forma de Onda");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Componente DC e Harmônicas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        panelHarmonicas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHarmonicas.setPreferredSize(new java.awt.Dimension(240, 220));
        jPanel1.add(panelHarmonicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 480, 370));

        panelOnda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOnda.setPreferredSize(new java.awt.Dimension(240, 220));
        jPanel1.add(panelOnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 480, 370));

        checkEquipamentos.setSelected(true);
        checkEquipamentos.setText("Todos os Equipamentos");
        checkEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEquipamentosActionPerformed(evt);
            }
        });
        jPanel1.add(checkEquipamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        CheckFase.setText("Mostrar liga (Fase)");
        CheckFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFaseActionPerformed(evt);
            }
        });
        jPanel1.add(CheckFase, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 170, -1));

        CheckFuga.setSelected(true);
        CheckFuga.setText("Mostrar Diferencial (Fuga)");
        CheckFuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFugaActionPerformed(evt);
            }
        });
        jPanel1.add(CheckFuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 220, -1));

        jTabbedPane1.addTab("Seleciona", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregaOndasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregaOndasActionPerformed
        // TODO add your handling code here:
        atualizaTabelaArquivadas();
    }//GEN-LAST:event_btnCarregaOndasActionPerformed

    private void radioDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDataActionPerformed
        // TODO add your handling code here:
        if (radioData.isSelected()){
            comboDataIni.setEnabled(true);
            comboDataFim.setEnabled(true);
        }
        else{
            comboDataIni.setEnabled(false);
            comboDataFim.setEnabled(false);
        }
    }//GEN-LAST:event_radioDataActionPerformed

    private void comboEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEquipamentoActionPerformed
        // TODO add your handling code here:
        Equipamento eqp = new Equipamento();
        if (comboEquipamento.getSelectedIndex() != -1) {
            eqp = (Equipamento) comboEquipamento.getSelectedItem();
            jtfEquipamento.setText(String.valueOf(eqp.getCodEquip()));
        }
    }//GEN-LAST:event_comboEquipamentoActionPerformed

    private void tabelaArquivadasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaArquivadasKeyReleased
        // TODO add your handling code here:
        if (tabelaArquivadas.getSelectedRow() != -1) {
            this.tabelaArquivadasMouseClicked(null);
        }
    }//GEN-LAST:event_tabelaArquivadasKeyReleased

    private void tabelaArquivadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaArquivadasMouseClicked
        // TODO add your handling code here:
        int linha = tabelaArquivadas.getSelectedRow();

        if (linha == -1){
            JOptionPane.showMessageDialog(null, "Não Existem Fugas");
            return;
        }

        bean = capdao.localiza((Integer) tabelaArquivadas.getValueAt(linha, 0));

        atualizaGraficos(bean, panelOnda, panelHarmonicas);
    }//GEN-LAST:event_tabelaArquivadasMouseClicked

    private void jtfEquipamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEquipamentoFocusLost
        // TODO add your handling code here:
        if (jtfEquipamento.getText().isEmpty()){
            comboEquipamento.setSelectedIndex(-1);
            return;
        }
        int codEquipamento = Integer.parseInt(jtfEquipamento.getText());
        Equipamento eqp = eqpdao.localiza(codEquipamento);
        if (eqp == null) {
            JOptionPane.showMessageDialog(null, "Equipamento não encontrado");
            if(comboEquipamento.getSelectedIndex() != -1){
                eqp = (Equipamento) comboEquipamento.getSelectedItem();
                jtfEquipamento.setText(String.valueOf(eqp.getCodEquip()));
            }
            return;
        } else {
            comboEquipamento.setSelectedItem((Equipamento)eqp);
        }
    }//GEN-LAST:event_jtfEquipamentoFocusLost

    private void jtfEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEquipamentoActionPerformed

    private void checkEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEquipamentosActionPerformed
        // TODO add your handling code here:
        if (! checkEquipamentos.isSelected()){
            txtEquipamento.setEnabled(true);
            jtfEquipamento.setEnabled(true);
            comboEquipamento.setEnabled(true);
        }
        else{
            txtEquipamento.setEnabled(false);
            jtfEquipamento.setEnabled(false);
            comboEquipamento.setEnabled(false);
        }
    }//GEN-LAST:event_checkEquipamentosActionPerformed

    private void CheckFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFaseActionPerformed
        // TODO add your handling code here:
        if (! CheckFuga.isSelected())
        if (! CheckFase.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Deve ser selecionapelo pelo menos um tipo de onda");
            CheckFase.setSelected(true);
        }
    }//GEN-LAST:event_CheckFaseActionPerformed

    private void CheckFugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFugaActionPerformed
        // TODO add your handling code here:
        if (! CheckFase.isSelected())
        if (! CheckFuga.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Deve ser selecionapelo pelo menos um tipo de onda");
            CheckFuga.setSelected(true);
        }
    }//GEN-LAST:event_CheckFugaActionPerformed
           
    private void atualizaGraficos (Object bean, JPanel panelOnda, JPanel panelHarmonicas){
        // Monta grafico da Onda        
        
        final JFreeChart chart = CriaGrafico.createChartLinhas(bean, false);
        final ChartPanel crtPanelOnda = new ChartPanel(chart);
        crtPanelOnda.setPreferredSize(new java.awt.Dimension(500, 370));
        
//        crtPanelOnda.setVisible(true);
//        crtPanelOnda.setSize(panelOnda.getWidth(), panelOnda.getHeight());
        
        panelOnda.removeAll();
        panelOnda.add(crtPanelOnda);
        panelOnda.revalidate();
        panelOnda.repaint();
                        
        // monta grafico de barras
        ChartPanel crtPanelBarras = new ChartPanel(CriaGrafico.createChartBarras(bean, false, true));
        crtPanelBarras.setPreferredSize(new java.awt.Dimension(500, 370));
        
        //crtPanelBarras.setVisible(true);
        //crtPanelBarras.setSize(panelHarmonicas.getWidth(), panelHarmonicas.getHeight());
        panelHarmonicas.removeAll();
        panelHarmonicas.add(crtPanelBarras);
        panelHarmonicas.revalidate();
        panelHarmonicas.repaint();
    }

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FormComparaArquivadas dialog = new FormComparaArquivadas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    private int montaTabelaArquivadas() {
        //Ajusta titulos da tabela
        titulosArquivadas.add("Captura");        
        titulosArquivadas.add("Tipo Evento");        
        titulosArquivadas.add("Sala");
        titulosArquivadas.add("Tomada");
        titulosArquivadas.add("Equipamento");                
        titulosArquivadas.add("Valor Medio");
        titulosArquivadas.add("Eficaz");                        
        titulosArquivadas.add("Data");        
        
        tabelaArquivadas.setModel(new DefaultTableModel(linhasArquivadas, titulosArquivadas));
        
        tabelaArquivadas.setAutoCreateRowSorter(true);

        return (linhasArquivadas.size());
    }

    private void atualizaTabelaArquivadas(){
        // inicializa os dados da tabela                
        Equipamento eqp;
        linhasArquivadas.clear();
        tabelaArquivadas.removeAll();    
        
        if (! checkEquipamentos.isSelected())
            eqp = (Equipamento) comboEquipamento.getSelectedItem();                            
        else        
            eqp = null;
        
        if (radioData.isSelected()){ //Se tem selecao de data
            String  sIni = (String) comboDataIni.getSelectedItem();        
            String  sFim = (String) comboDataFim.getSelectedItem();                             
            
            for (CapturaAtual c : capdao.listacFO(eqp, Conversoes.StringToCalendar(sIni), Conversoes.StringToCalendar(sFim), CheckFase.isSelected(), CheckFuga.isSelected() ) ) 
                addTabelaArquivadas(c);            
        }
        else{
            for (CapturaAtual c : capdao.listacFO(eqp, CheckFase.isSelected(), CheckFuga.isSelected()) ) 
                addTabelaArquivadas(c);            
        }
        
        JOptionPane.showMessageDialog(panelHarmonicas, "Foram adicionados " + tabelaArquivadas.getRowCount() + " eventos");
 
        tabelaArquivadas.revalidate();                        
    }    
    
    private void addTabelaArquivadas(CapturaAtual c) {
              
        Vector colunas = new Vector();

        colunas.add(c.getCodCaptura());
        colunas.add(c.getCodEvento().getCodEvento() == 1 ? "Fuga": "Liga");
        colunas.add(c.getCodTomada().getCodSala());
        colunas.add(c.getCodTomada());        
        colunas.add(c.getCodEquip());
        colunas.add(c.getValorMedio());
        colunas.add(c.getEficaz());        
        colunas.add(Conversoes.CalendarToTimeStamp(c.getDataAtual()));                        

        linhasArquivadas.add(colunas);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckFase;
    private javax.swing.JCheckBox CheckFuga;
    private javax.swing.ButtonGroup GrupoOndas;
    private javax.swing.JButton btnCarregaOndas;
    private javax.swing.JCheckBox checkEquipamentos;
    private javax.swing.JComboBox comboDataFim;
    private javax.swing.JComboBox comboDataIni;
    private javax.swing.JComboBox comboEquipamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtfEquipamento;
    private javax.swing.JPanel panelHarmonicas;
    private javax.swing.JPanel panelHarmonicas1;
    private javax.swing.JPanel panelHarmonicas2;
    private javax.swing.JPanel panelOnda;
    private javax.swing.JPanel panelOnda1;
    private javax.swing.JCheckBox radioData;
    private javax.swing.JTable tabelaArquivadas;
    private javax.swing.JLabel txtEquipamento;
    // End of variables declaration//GEN-END:variables

}
