/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormFugas.java
 *
 * Created on Nov 4, 2011, 8:12:28 AM
 *
 * @author rebonatto
 */

package Visualizacao;

import Graficos.CriaGrafico;
import Similaridade.Funcoes;
import Similaridade.GraficosSimilaridade;
import Uteis.Configuracoes;
import Uteis.Cores;
import Uteis.FormataNumeros;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.CapturaAtual;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import persistencia.CapturaAtualDAO;
import persistencia.FugasDAO;

/**
 *
 * @author rebonatto
 */
public class FormComparaOndas extends javax.swing.JDialog {    
    private CapturaAtualDAO capdao = new CapturaAtualDAO();    
    private FugasDAO fugdao = new FugasDAO();
    
    private Vector<CapturaAtual> fugas = new Vector<CapturaAtual>();
        
    private CapturaAtual bean = new CapturaAtual();    
    
    Vector titulosFugas = new Vector();
    Vector linhasFugas = new Vector();
    
    Vector titulosCompara = new Vector();
    Vector linhasCompara = new Vector();
    
    /** Creates new form FormEquipamento */
    public FormComparaOndas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setTitle("Waveform Comparasion");
        
        //preenche o combobox                       
        
        titulosFugas.add("Capture");        
        titulosFugas.add("Room");
        titulosFugas.add("Outlet");
        titulosFugas.add("Equipment");                
        titulosFugas.add("Mean Value");
        titulosFugas.add("RMS");                                        
        
        tabelaFugas.setModel(new DefaultTableModel(linhasFugas, titulosFugas));
        
        titulosCompara.add("Leakage 1");        
        titulosCompara.add("Leakage 2");
        titulosCompara.add("Pearson");
        titulosCompara.add("Spearman");                
        titulosCompara.add("Shift");
                                                
        tabelaCompara.setModel(new DefaultTableModel(linhasCompara, titulosCompara));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoOndas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaCompara = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        panelOnda = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelDeslocadas = new javax.swing.JPanel();
        panelHarmonicas = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaFugas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Codigo5 = new javax.swing.JTextField();
        Codigo1 = new javax.swing.JTextField();
        Codigo2 = new javax.swing.JTextField();
        Codigo3 = new javax.swing.JTextField();
        Codigo4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaCompara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaCompara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaComparaMouseClicked(evt);
            }
        });
        tabelaCompara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaComparaKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tabelaCompara);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 790, 140));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("Waveform");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 250, -1, 30));

        panelOnda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOnda.setPreferredSize(new java.awt.Dimension(240, 220));
        jPanel1.add(panelOnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 430, 390));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setText("DC and Harmonics");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 250, -1, 30));

        panelDeslocadas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDeslocadas.setPreferredSize(new java.awt.Dimension(240, 220));
        jPanel1.add(panelDeslocadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 430, 390));

        panelHarmonicas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHarmonicas.setPreferredSize(new java.awt.Dimension(240, 220));
        jPanel1.add(panelHarmonicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 430, 390));

        tabelaFugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelaFugas);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 790, 80));

        jLabel1.setText("Waveform5:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel2.setText("Waveform1:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setText("Waveform2:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel6.setText("Waveform3:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel7.setText("Waveform4:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        Codigo5.setName("Waveform5"); // NOI18N
        jPanel1.add(Codigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, -1));

        Codigo1.setName("Waveform1"); // NOI18N
        jPanel1.add(Codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        Codigo2.setName("Waveform2"); // NOI18N
        jPanel1.add(Codigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));

        Codigo3.setName("Waveform3"); // NOI18N
        jPanel1.add(Codigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, -1));

        Codigo4.setName("Waveform4"); // NOI18N
        jPanel1.add(Codigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 90, -1));

        jButton1.setText("Clean");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setText("Waveform with Shift");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 250, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void atualizaComparacoes(){
        int i, j;
        linhasCompara.clear();
        tabelaCompara.removeAll();
                
        List<Double> onda1List = new ArrayList<Double>();
        List<Double> onda2List = new ArrayList<Double>();                
        
        double pearson[], spearman[];        
        
        for(i=0; i < fugas.size(); i++){
            for(j = i+1; j < fugas.size(); j++){
                onda1List = Funcoes.retListO(fugas.get(i));
                onda2List = Funcoes.retListO(fugas.get(j));
                
                pearson = Funcoes.pearson(onda1List, onda2List);
                spearman = Funcoes.spearman(onda1List, onda2List);
                                
                Vector colunas = new Vector();

                colunas.add(fugas.get(i));
                colunas.add(fugas.get(j));
                colunas.add(Funcoes.casasDouble(pearson[0], 4));
                colunas.add(Funcoes.casasDouble(spearman[0], 4));
                colunas.add((int) spearman[1]);

                linhasCompara.add(colunas);
            }
        }
        tabelaCompara.repaint();
        tabelaCompara.revalidate();
        
    }
    
    private void tabelaComparaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaComparaMouseClicked
        // TODO add your handling code here:
        int pos1, pos2;
        int linha = tabelaCompara.getSelectedRow();                

        if (linha == -1){
            JOptionPane.showMessageDialog(null, "Waveforms not found");
            return;
        }
        
        CapturaAtual onda1 = (CapturaAtual) tabelaCompara.getValueAt(linha, 0);
        pos1 = Cores.getposicao(tabelaFugas, onda1.getCodCaptura());
        CapturaAtual onda2 = (CapturaAtual) tabelaCompara.getValueAt(linha, 1);
        pos2 = Cores.getposicao(tabelaFugas, onda2.getCodCaptura());
                
        double correlacao  = (double) tabelaCompara.getValueAt(linha, 3); // Spearman
        int deslocamento   = (int) tabelaCompara.getValueAt(linha, 4);
                
        //monta grafico primeira e deslocada        
        final ChartPanel crtPanelOnda ;
        crtPanelOnda = new ChartPanel(GraficosSimilaridade.criaGrafico2LinhasComDeslocada(onda1, onda2, deslocamento, correlacao, Cores.getCorGrafico(pos1), Cores.getCorGrafico(pos2)));
        crtPanelOnda.setPreferredSize(new java.awt.Dimension(420, 380));
        panelDeslocadas.removeAll();
        panelDeslocadas.add(crtPanelOnda);
        panelDeslocadas.revalidate();
        panelDeslocadas.repaint();
        
    }//GEN-LAST:event_tabelaComparaMouseClicked

    private void tabelaComparaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaComparaKeyReleased
        // TODO add your handling code here:
                // TODO add your handling code here:
        if (tabelaCompara.getSelectedRow() != -1) {
            this.tabelaComparaMouseClicked(null);
        }
    }//GEN-LAST:event_tabelaComparaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Codigo1.setText("");
        Codigo2.setText("");
        Codigo3.setText("");
        Codigo4.setText("");
        Codigo5.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        atualizaTabelaFugas();
    }//GEN-LAST:event_jButton2ActionPerformed
           
    private void atualizaGraficos (){                        
        // Monta grafico das Ondas                
        final JFreeChart chart = CriaGrafico.criaGraficoComparaLinhas(fugas);
        final ChartPanel crtPanelOnda = new ChartPanel(chart);
        crtPanelOnda.setPreferredSize(new java.awt.Dimension(420, 380));

//        crtPanelOnda.setVisible(true);
//        crtPanelOnda.setSize(panelOnda.getWidth(), panelOnda.getHeight());

        panelOnda.removeAll();
        panelOnda.add(crtPanelOnda);
        panelOnda.revalidate();
        panelOnda.repaint();                
        
        // monta grafico das barras
        ChartPanel crtPanelBarras = new ChartPanel(CriaGrafico.criaGraficoComparaBarras(fugas));
        crtPanelBarras.setPreferredSize(new java.awt.Dimension(420, 380));

        //crtPanelBarras.setVisible(true);
        //crtPanelBarras.setSize(panelHarmonicas.getWidth(), panelHarmonicas.getHeight());
        panelHarmonicas.removeAll();
        panelHarmonicas.add(crtPanelBarras);
        panelHarmonicas.revalidate();
        panelHarmonicas.repaint();
        
        
        // limpa o grafico das deslocadas
        panelDeslocadas.removeAll();
        panelDeslocadas.revalidate();
        panelDeslocadas.repaint();                
    }

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FormComparaOndas dialog = new FormComparaOndas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }                
    
    private void atualizaTabelaFugas(){                                                 
        // inicializa os dados da tabela                        
        linhasFugas.clear();
        tabelaFugas.removeAll();               
        fugas.removeAllElements();
                
        addTabelaFugas(Codigo1);
        addTabelaFugas(Codigo2);
        addTabelaFugas(Codigo3);
        addTabelaFugas(Codigo4);
        addTabelaFugas(Codigo5);        
        
        tabelaFugas.revalidate();
        tabelaFugas.repaint();
        
        atualizaComparacoes();
        atualizaGraficos();
    }
    
    private void addTabelaFugas(JTextField edit) {
        int cod = 0;      
        CapturaAtual cap;
        if (! edit.getText().isEmpty()){
            try{       
                cod = Integer.parseInt(edit.getText());
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Value in " + edit.getName() + " Invalido");
                edit.requestFocus();
            }
        
            cap = capdao.localiza(cod);
            if (cap != null){               
                Vector colunas = new Vector();

                colunas.add(cap.getCodCaptura());                        
                colunas.add(cap.getCodTomada().getCodSala());
                colunas.add(cap.getCodTomada());        
                colunas.add(cap.getCodEquip());
                
                if (cap.getDataAtual().compareTo(Configuracoes.DATALIMITEVM) < 0){ // Menor que zero significa data da captura e antes de 01/01/2015
                    colunas.add((int) cap.getValorMedio() / Configuracoes.PONTOSONDA);
                    //System.out.println("Colocou o valor dividio por 256");
                }
                else{
                    colunas.add( (int) cap.getValorMedio() );
                    //System.out.println("Colocou o valor real");
                }
                
                
                colunas.add(FormataNumeros.FormataSignificativos(cap.getEficaz(), Configuracoes.DIGITOSSIGNIFICATIVOS));                    

                fugas.add(cap);
                
                linhasFugas.add(colunas);
            }
            else {
                JOptionPane.showMessageDialog(null, "Waveform " + edit.getText() + " not found");
                edit.requestFocus();
            }
        }                   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo1;
    private javax.swing.JTextField Codigo2;
    private javax.swing.JTextField Codigo3;
    private javax.swing.JTextField Codigo4;
    private javax.swing.JTextField Codigo5;
    private javax.swing.ButtonGroup GrupoOndas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel panelDeslocadas;
    private javax.swing.JPanel panelHarmonicas;
    private javax.swing.JPanel panelOnda;
    private javax.swing.JTable tabelaCompara;
    private javax.swing.JTable tabelaFugas;
    // End of variables declaration//GEN-END:variables

}
