/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacao;


import Graficos.CriaGrafico;
import Uteis.CalendarComboBox;
import Uteis.Configuracoes;
import Uteis.Conversoes;
import Uteis.FormataNumeros;
import java.awt.FlowLayout;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.CapturaAtual;
import modelo.Equipamento;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import persistencia.CapturaAtualDAO;
import persistencia.EquipamentoDAO;
import persistencia.EventoDAO;

/**
 *
 * @author rebonatto
 */

public class FormMostraUmaOnda extends javax.swing.JDialog {
    private EquipamentoDAO eqpdao = new EquipamentoDAO();
    private EventoDAO evdao = new EventoDAO();
    private CapturaAtualDAO dao = new CapturaAtualDAO();
    private CapturaAtual bean = new CapturaAtual();
    

    /**
     * Creates new form FormFoCapturadas
     */
    public FormMostraUmaOnda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //System.out.println("Executando");
        initComponents();
                
        setTitle("Showing one Waveform stored");
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHarmonicas = new javax.swing.JPanel();
        panelOnda = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfOnda = new javax.swing.JTextField();
        btnMostraOnda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        det = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHarmonicas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHarmonicas.setPreferredSize(new java.awt.Dimension(240, 220));
        getContentPane().add(panelHarmonicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 500, 370));

        panelOnda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOnda.setPreferredSize(new java.awt.Dimension(240, 220));
        getContentPane().add(panelOnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 500, 370));

        jLabel4.setText("esp");
        jLabel4.setEnabled(false);
        jLabel4.setFocusable(false);
        jLabel4.setRequestFocusEnabled(false);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, -1, -1));

        jLabel5.setText("espaco");
        jLabel5.setEnabled(false);
        jLabel5.setFocusable(false);
        jLabel5.setRequestFocusEnabled(false);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, -1, 20));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DC and Harmonics");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 480, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Waveform");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 220, 480, -1));

        jLabel7.setText("Capture:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jtfOnda.setText("5273263");
        jtfOnda.setToolTipText("");
        getContentPane().add(jtfOnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, -1));

        btnMostraOnda.setText("Plot");
        btnMostraOnda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraOndaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostraOnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        det.setColumns(20);
        det.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        det.setRows(5);
        jScrollPane1.setViewportView(det);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 470, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    
    private void atualizaGraficos (CapturaAtual evento){
        // Monta grafico da Onda        
        final JFreeChart chart = CriaGrafico.createChartLinhas(evento, false);
        final ChartPanel crtPanelOnda = new ChartPanel(chart);
        crtPanelOnda.setPreferredSize(new java.awt.Dimension(500, 370));
        
//        crtPanelOnda.setVisible(true);
//        crtPanelOnda.setSize(panelOnda.getWidth(), panelOnda.getHeight());
        
        panelOnda.removeAll();
        panelOnda.add(crtPanelOnda);
        panelOnda.revalidate();
        panelOnda.repaint();
                        
        // monta grafico de barras
        ChartPanel crtPanelBarras = new ChartPanel(CriaGrafico.createChartBarras(evento, false, true));
        crtPanelBarras.setPreferredSize(new java.awt.Dimension(500, 370));
        
        //crtPanelBarras.setVisible(true);
        //crtPanelBarras.setSize(panelHarmonicas.getWidth(), panelHarmonicas.getHeight());
        panelHarmonicas.removeAll();
        panelHarmonicas.add(crtPanelBarras);
        panelHarmonicas.revalidate();
        panelHarmonicas.repaint();
        
       det.setText("");
        
        det.append("Time: " + Conversoes.CalendarToStringDH(evento.getDataAtual()) + " ");        
        det.append("RMS: " + FormataNumeros.FormataSignificativos(evento.getEficaz(), Configuracoes.DIGITOSSIGNIFICATIVOS)+ "\n");
        det.append("Equipment: " + evento.getCodEquip().getDesc() + "\n" + 
                         evento.getCodEquip().getCodMarca().getDesc().trim() + " - " + 
                         evento.getCodEquip().getCodModelo().getDesc().trim() +  "\n"+
                         "RFID: " + evento.getCodEquip().getRfid());
    }
    
    private void btnMostraOndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraOndaActionPerformed
        // TODO add your handling code here:
        CapturaAtual bean = dao.localiza(Integer.parseInt(jtfOnda.getText()));
        
        atualizaGraficos(bean);
//        
//        final JFreeChart chart = CriaGrafico.createChartLinhas(bean, false);
//        final ChartPanel crtPanelOnda = new ChartPanel(chart);
//        crtPanelOnda.setPreferredSize(new java.awt.Dimension(500, 370));
//        
////        crtPanelOnda.setVisible(true);
////        crtPanelOnda.setSize(panelOnda.getWidth(), panelOnda.getHeight());
//        
//        panelOnda.removeAll();
//        panelOnda.add(crtPanelOnda);
//        panelOnda.revalidate();
//        panelOnda.repaint();
//                        
//        // monta grafico de barras
//        ChartPanel crtPanelBarras = new ChartPanel(CriaGrafico.createChartBarras(bean, false, true));
//        crtPanelBarras.setPreferredSize(new java.awt.Dimension(500, 370));
//        
//        //crtPanelBarras.setVisible(true);
//        //crtPanelBarras.setSize(panelHarmonicas.getWidth(), panelHarmonicas.getHeight());
//        panelHarmonicas.removeAll();
//        panelHarmonicas.add(crtPanelBarras);
//        panelHarmonicas.revalidate();
//        panelHarmonicas.repaint();
    }//GEN-LAST:event_btnMostraOndaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMostraUmaOnda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMostraUmaOnda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMostraUmaOnda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMostraUmaOnda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMostraUmaOnda dialog = new FormMostraUmaOnda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostraOnda;
    private javax.swing.JTextArea det;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfOnda;
    private javax.swing.JPanel panelHarmonicas;
    private javax.swing.JPanel panelOnda;
    // End of variables declaration//GEN-END:variables

}
