/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormFugas.java
 *
 * Created on Nov 4, 2011, 8:12:28 AM
 *
 * @author rebonatto
 */

package Visualizacao;

import Graficos.CriaGrafico;
import Uteis.Conversoes;
import Uteis.CalendarComboBox;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Formularios.BeanFuga;
import modelo.CapturaAtual;
import modelo.Equipamento;
import modelo.OndaPadrao;
import modelo.TipoPadrao;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import persistencia.CapturaAtualDAO;
import persistencia.EquipamentoDAO;
import persistencia.FugasDAO;
import persistencia.OndaPadraoDAO;
import persistencia.TipoPadraoDAO;

/**
 *
 * @author rebonatto
 */
public class FormFugas extends javax.swing.JDialog {
    private OndaPadraoDAO dao = new OndaPadraoDAO();
    private CapturaAtualDAO capdao = new CapturaAtualDAO();
    private EquipamentoDAO eqpdao = new EquipamentoDAO();
    private TipoPadraoDAO tipdao = new TipoPadraoDAO();
    private FugasDAO fugdao = new FugasDAO();
    
    private OndaPadrao bean = new OndaPadrao();
    private CapturaAtual cap = new CapturaAtual();
    private BeanFuga fuga = new BeanFuga();

    
    Vector titulosOnLine = new Vector();
    Vector linhasOnLine = new Vector();

    Vector titulosArquivadas = new Vector();
    Vector linhasArquivadas = new Vector();

    
    /** Creates new form FormEquipamento */
    public FormFugas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //preenche o combobox       
        comboArquivadasEquip.removeAllItems();        
        comboConEquipamento.removeAllItems();
        for (Equipamento equip : eqpdao.lista()) {
            comboArquivadasEquip.addItem((Equipamento) equip);
            comboConEquipamento.addItem((Equipamento) equip);
        }

        setTitle("Formulário de Fugas");
        
        if (montaTabelaOnLine() == 0) {
            JOptionPane.showMessageDialog(this, "Tabela Vazia");
        }
        
        montaTabelaArquivadas() ;         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoOndas = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaOnLine = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jtfConEquipamento = new javax.swing.JTextField();
        comboConEquipamento = new javax.swing.JComboBox();
        radioEquip = new javax.swing.JCheckBox();
        panelPadraoOnda = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelPadraoHarmonicas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAtualizaOndasPadrao = new javax.swing.JButton();
        tabCadastro = new javax.swing.JPanel();
        comboDataFim = new CalendarComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtfArquivadasEquip = new javax.swing.JTextField();
        btnFiltrar1 = new javax.swing.JButton();
        btnLimparFiltro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaArquivadas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelOnda = new javax.swing.JPanel();
        panelHarmonicas = new javax.swing.JPanel();
        comboArquivadasEquip = new javax.swing.JComboBox();
        radioData = new javax.swing.JCheckBox();
        btnCarregaOndas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboDataIni = new CalendarComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaOnLine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaOnLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaOnLineMouseClicked(evt);
            }
        });
        tabelaOnLine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaOnLineKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaOnLine);

        jLabel4.setText("Equipamento:");

        jtfConEquipamento.setEnabled(false);
        jtfConEquipamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfConEquipamentoFocusLost(evt);
            }
        });

        comboConEquipamento.setEditable(true);
        comboConEquipamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboConEquipamento.setEnabled(false);
        comboConEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConEquipamentoActionPerformed(evt);
            }
        });

        radioEquip.setText("Escolher um Equipamento");
        radioEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEquipActionPerformed(evt);
            }
        });

        panelPadraoOnda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPadraoOnda.setPreferredSize(new java.awt.Dimension(240, 220));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Forma de Onda");

        panelPadraoHarmonicas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPadraoHarmonicas.setPreferredSize(new java.awt.Dimension(240, 220));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Componente DC e Harmônicas");

        btnAtualizaOndasPadrao.setText("Atualiza Tabela");
        btnAtualizaOndasPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaOndasPadraoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabConsultaLayout = new javax.swing.GroupLayout(tabConsulta);
        tabConsulta.setLayout(tabConsultaLayout);
        tabConsultaLayout.setHorizontalGroup(
            tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1353, Short.MAX_VALUE)
                    .addGroup(tabConsultaLayout.createSequentialGroup()
                        .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioEquip)
                            .addGroup(tabConsultaLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jtfConEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(comboConEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnAtualizaOndasPadrao)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(tabConsultaLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabConsultaLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel7)
                        .addGap(331, 331, 331)
                        .addComponent(jLabel5))
                    .addGroup(tabConsultaLayout.createSequentialGroup()
                        .addComponent(panelPadraoOnda, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(panelPadraoHarmonicas, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabConsultaLayout.setVerticalGroup(
            tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConsultaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(radioEquip)
                .addGap(18, 18, 18)
                .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabConsultaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(jtfConEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboConEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAtualizaOndasPadrao)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPadraoOnda, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPadraoHarmonicas, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("On-line", tabConsulta);

        tabCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboDataFim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDataFim.setEnabled(false);
        tabCadastro.add(comboDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 124, -1));

        jLabel3.setText("Equipamento:");
        tabCadastro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        jtfArquivadasEquip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfArquivadasEquipFocusLost(evt);
            }
        });
        tabCadastro.add(jtfArquivadasEquip, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 62, -1));

        btnFiltrar1.setText("FiltrarEquipamento");
        btnFiltrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrar1ActionPerformed(evt);
            }
        });
        tabCadastro.add(btnFiltrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 160, -1));

        btnLimparFiltro.setText("Limpar Filtro Equip");
        btnLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFiltroActionPerformed(evt);
            }
        });
        tabCadastro.add(btnLimparFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 130, -1));

        tabelaArquivadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaArquivadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaArquivadasMouseClicked(evt);
            }
        });
        tabelaArquivadas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaArquivadasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaArquivadas);

        tabCadastro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1340, 180));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Forma de Onda");
        tabCadastro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Componente DC e Harmônicas");
        tabCadastro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        panelOnda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOnda.setPreferredSize(new java.awt.Dimension(240, 220));
        tabCadastro.add(panelOnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 480, 370));

        panelHarmonicas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHarmonicas.setPreferredSize(new java.awt.Dimension(240, 220));
        tabCadastro.add(panelHarmonicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 480, 370));

        comboArquivadasEquip.setEditable(true);
        comboArquivadasEquip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboArquivadasEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboArquivadasEquipActionPerformed(evt);
            }
        });
        tabCadastro.add(comboArquivadasEquip, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 234, -1));

        radioData.setText("Selecionar Data");
        radioData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDataActionPerformed(evt);
            }
        });
        tabCadastro.add(radioData, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        btnCarregaOndas.setText("Carregar Fugas");
        btnCarregaOndas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregaOndasActionPerformed(evt);
            }
        });
        tabCadastro.add(btnCarregaOndas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, 30));

        jLabel1.setText("Até:");
        tabCadastro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        jLabel9.setText("De:");
        tabCadastro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        comboDataIni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDataIni.setEnabled(false);
        tabCadastro.add(comboDataIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 124, -1));

        jTabbedPane1.addTab("Arquivadas", tabCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
           
    private void tabelaOnLineKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaOnLineKeyReleased
        // TODO add your handling code here:
         if (tabelaOnLine.getSelectedRow() != -1) {         
            //System.out.println(tabelaPadrao.getSelectedRow());
            this.tabelaOnLineMouseClicked(null);
        }
    }//GEN-LAST:event_tabelaOnLineKeyReleased

    private void jtfArquivadasEquipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfArquivadasEquipFocusLost
        // TODO add your handling code here:
        if (jtfArquivadasEquip.getText().isEmpty()){
            comboArquivadasEquip.setSelectedIndex(-1);
            return;
        }
        int codEquipamento = Integer.parseInt(jtfArquivadasEquip.getText());
        Equipamento eqp = eqpdao.localiza(codEquipamento);
        if (eqp == null) {
            JOptionPane.showMessageDialog(null, "Equipamento não encontrado");
            if(comboArquivadasEquip.getSelectedIndex() != -1){
                eqp = (Equipamento) comboArquivadasEquip.getSelectedItem();
                jtfArquivadasEquip.setText(String.valueOf(eqp.getCodEquip()));
            }
            return;
        } else {
            comboArquivadasEquip.setSelectedItem((Equipamento)eqp);
        }
    }//GEN-LAST:event_jtfArquivadasEquipFocusLost

    private void tabelaArquivadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaArquivadasMouseClicked
        // TODO add your handling code here:
        int linha = tabelaArquivadas.getSelectedRow();

        if (linha == -1){
            JOptionPane.showMessageDialog(null, "Não Existem Fugas");
            return;
        }        
               
        fuga = fugdao.localiza((Integer) tabelaArquivadas.getValueAt(linha, 0));
        
        atualizaGraficos(fuga, panelOnda, panelHarmonicas);
    }//GEN-LAST:event_tabelaArquivadasMouseClicked

    private void tabelaArquivadasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaArquivadasKeyReleased
        // TODO add your handling code here:
        if (tabelaArquivadas.getSelectedRow() != -1) {
            this.tabelaArquivadasMouseClicked(null);
        }
    }//GEN-LAST:event_tabelaArquivadasKeyReleased

    private void comboArquivadasEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboArquivadasEquipActionPerformed
        // TODO add your handling code here:
        Equipamento eqp = new Equipamento();
        if (comboArquivadasEquip.getSelectedIndex() != -1) {
            eqp = (Equipamento) comboArquivadasEquip.getSelectedItem();
            jtfArquivadasEquip.setText(String.valueOf(eqp.getCodEquip()));
        }        

    }//GEN-LAST:event_comboArquivadasEquipActionPerformed

    private void jtfConEquipamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfConEquipamentoFocusLost
        // TODO add your handling code here:        
        System.out.println("Entrou perda de foco");
        if (jtfConEquipamento.getText().isEmpty()){
            comboConEquipamento.setSelectedIndex(-1);
            return;
        }
        int codEquipamento = Integer.parseInt(jtfConEquipamento.getText());
        Equipamento eqp = eqpdao.localiza(codEquipamento);
        
        if (eqp == null) {
            JOptionPane.showMessageDialog(null, "Equipamento não encontrado");
            if(comboConEquipamento.getSelectedIndex() != -1){
                eqp = (Equipamento) comboConEquipamento.getSelectedItem();
                jtfConEquipamento.setText(String.valueOf(eqp.getCodEquip()));
            }
            return;
        } else {
            comboConEquipamento.setSelectedItem((Equipamento) eqp);            
        }   
    }//GEN-LAST:event_jtfConEquipamentoFocusLost

    private void comboConEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConEquipamentoActionPerformed
        // TODO add your handling code here:
        Equipamento eqp = new Equipamento();
        if (comboConEquipamento.getSelectedIndex() != -1) {
            eqp = (Equipamento) comboConEquipamento.getSelectedItem();
            jtfConEquipamento.setText(String.valueOf(eqp.getCodEquip()));
        }        
        
    }//GEN-LAST:event_comboConEquipamentoActionPerformed

    private void radioEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEquipActionPerformed
        // TODO add your handling code here:
        if (radioEquip.isSelected()){
            jtfConEquipamento.setEnabled(true);
            comboConEquipamento.setEnabled(true);
            btnAtualizaOndasPadrao.setEnabled(true);
        }
        else{
            atualizaTabelaOnLine(null);
            jtfConEquipamento.setEnabled(false);
            comboConEquipamento.setEnabled(false);            
            btnAtualizaOndasPadrao.setEnabled(false);
        }
    }//GEN-LAST:event_radioEquipActionPerformed

    private void radioDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDataActionPerformed
        // TODO add your handling code here:
        if (radioData.isSelected()){
            comboDataIni.setEnabled(true);
            comboDataFim.setEnabled(true);            
        }
        else{
            comboDataIni.setEnabled(false);
            comboDataFim.setEnabled(false);            
        }
    }//GEN-LAST:event_radioDataActionPerformed

    private void tabelaOnLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaOnLineMouseClicked
        // TODO add your handling code here:
        int linha = tabelaOnLine.getSelectedRow();

        if (linha == -1){
            JOptionPane.showMessageDialog(null, "Equipamento sem Ondas Cadastradas");
            return;
        }        
               
        bean = dao.localiza((Integer) tabelaOnLine.getValueAt(linha, 0));
        
        atualizaGraficos(bean, panelPadraoOnda, panelPadraoHarmonicas);
    }//GEN-LAST:event_tabelaOnLineMouseClicked

    private void btnLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFiltroActionPerformed
        // TODO add your handling code here:
        comboArquivadasEquip.removeAllItems();
        for (Equipamento equip : eqpdao.lista()) {
            comboArquivadasEquip.addItem((Equipamento) equip);
        }
    }//GEN-LAST:event_btnLimparFiltroActionPerformed

    private void btnFiltrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrar1ActionPerformed
        // TODO add your handling code here:

        FormFiltroEquip.ObjFiltroEquip obj = FormFiltroEquip.abreFormulario();

        if ( (obj.isSelTipo()) || obj.isSelMarca() || obj.isSelModelo()){
            comboArquivadasEquip.removeAllItems();
            if (! obj.isSelTipo())
            obj.setCodTipo(null);
            if (! obj.isSelMarca())
            obj.setCodMarca(null);
            if (! obj.isSelModelo())
            obj.setCodModelo(null);

            for (Equipamento equip : eqpdao.lista(obj.getCodTipo(), obj.getCodMarca(), obj.getCodModelo())) {
                comboArquivadasEquip.addItem((Equipamento) equip);
            }
        }
    }//GEN-LAST:event_btnFiltrar1ActionPerformed

    private void btnCarregaOndasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregaOndasActionPerformed
        // TODO add your handling code here:
        atualizaTabelaArquivadas();
    }//GEN-LAST:event_btnCarregaOndasActionPerformed

    private void btnAtualizaOndasPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaOndasPadraoActionPerformed
        // TODO add your handling code here:
        Equipamento eqp = (Equipamento) comboConEquipamento.getSelectedItem();
        atualizaTabelaOnLine(eqp);
    }//GEN-LAST:event_btnAtualizaOndasPadraoActionPerformed

    private void atualizaGraficos (Object bean, JPanel panelOnda, JPanel panelHarmonicas){
        // Monta grafico da Onda        
        BeanFuga bf  = (BeanFuga) bean;
        final JFreeChart chart = CriaGrafico.createChartLinhas(bf.getCaptura(), false);
        final ChartPanel crtPanelOnda = new ChartPanel(chart);
        crtPanelOnda.setPreferredSize(new java.awt.Dimension(500, 370));
        
//        crtPanelOnda.setVisible(true);
//        crtPanelOnda.setSize(panelOnda.getWidth(), panelOnda.getHeight());
        
        panelOnda.removeAll();
        panelOnda.add(crtPanelOnda);
        panelOnda.revalidate();
        panelOnda.repaint();
                        
        // monta grafico de barras
        ChartPanel crtPanelBarras = new ChartPanel(CriaGrafico.createChartBarras(bf.getCaptura(), false, true));
        crtPanelBarras.setPreferredSize(new java.awt.Dimension(500, 370));
        
        //crtPanelBarras.setVisible(true);
        //crtPanelBarras.setSize(panelHarmonicas.getWidth(), panelHarmonicas.getHeight());
        panelHarmonicas.removeAll();
        panelHarmonicas.add(crtPanelBarras);
        panelHarmonicas.revalidate();
        panelHarmonicas.repaint();
    }

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FormFugas dialog = new FormFugas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private int montaTabelaOnLine() {
        //Ajusta titulos da tabela
        titulosOnLine.add("Código");        
        titulosOnLine.add("Equipamento");
        titulosOnLine.add("TipoPadrao");
        titulosOnLine.add("Sala");
        titulosOnLine.add("Tomada");
        titulosOnLine.add("Data");        
        titulosOnLine.add("Valor Medio");
        titulosOnLine.add("Eficaz");                
        
        atualizaTabelaOnLine(null);
        
        tabelaOnLine.setModel(new DefaultTableModel(linhasOnLine, titulosOnLine));

        return (linhasOnLine.size());
    }

    private void atualizaTabelaOnLine(Equipamento eqp){
        // inicializa os dados da tabela
        
        linhasOnLine.clear();
        tabelaOnLine.removeAll();        
        if (eqp == null){
            for (OndaPadrao op : dao.lista()) {
                addTabelaOnLine(op);
            }
        }
        else{
            for (OndaPadrao op : dao.lista(eqp)) {
                addTabelaOnLine(op);
            }
        }
        tabelaOnLine.revalidate();                
    }    
    
    private void addTabelaOnLine(OndaPadrao p) {
        Vector colunas = new Vector();
        
        colunas.add(p.getCodOndaPadrao());
        colunas.add(p.getCodEquip());
        colunas.add(p.getCodTipoPadrao());
        colunas.add(p.getCodTomada().getCodSala());
        colunas.add(p.getCodTomada());
        colunas.add(Conversoes.CalendarToTimeStamp(p.getDataPadrao()));
        colunas.add(p.getValorMedio());
        colunas.add(p.getEficaz());

        linhasOnLine.add(colunas);
    }
    
    private int montaTabelaArquivadas() {
        //Ajusta titulos da tabela
        titulosArquivadas.add("Captura");        
        titulosArquivadas.add("Sala");
        titulosArquivadas.add("Tomada");
        titulosArquivadas.add("Equipamento");                
        titulosArquivadas.add("Valor Medio");
        titulosArquivadas.add("Eficaz");                        
        titulosArquivadas.add("Inicio");        
        titulosArquivadas.add("Fim");        
        titulosArquivadas.add("Duração");        
        
        tabelaArquivadas.setModel(new DefaultTableModel(linhasArquivadas, titulosArquivadas));
        tabelaArquivadas.setAutoCreateRowSorter(true);

        return (linhasArquivadas.size());
    }

    private void atualizaTabelaArquivadas(){
        // inicializa os dados da tabela                
        linhasArquivadas.clear();
        tabelaArquivadas.removeAll();        
        Equipamento eqp = (Equipamento) comboArquivadasEquip.getSelectedItem();               
        
        for (BeanFuga fug : fugdao.lista() ) {
            addTabelaArquivadas(fug);
        }        
        
        if (radioData.isSelected()){ //Se tem selecao de data
            String  sIni = (String) comboDataIni.getSelectedItem();        
            String  sFim = (String) comboDataFim.getSelectedItem();        
            for (BeanFuga bf : fugdao.lista(eqp, Conversoes.StringToCalendar(sIni), Conversoes.StringToCalendar(sFim)) ) {
                addTabelaArquivadas(bf);
            }
        }
        else{
            for (BeanFuga bf : fugdao.lista(eqp) ) {
                addTabelaArquivadas(bf);
            }

        }
 
        tabelaArquivadas.revalidate();                        
    }    
    
    private void addTabelaArquivadas(BeanFuga bf) {
        if ( bf.getTermino() != null){
        
            Vector colunas = new Vector();

            colunas.add(bf.getCaptura().getCodCaptura());
            colunas.add(bf.getCaptura().getCodTomada().getCodSala());
            colunas.add(bf.getCaptura().getCodTomada());        
            colunas.add(bf.getCaptura().getCodEquip());
            colunas.add(bf.getCaptura().getValorMedio());
            colunas.add(bf.getCaptura().getEficaz());        
            colunas.add(Conversoes.CalendarToTimeStamp(bf.getCaptura().getDataAtual()));
            colunas.add(Conversoes.CalendarToTime(bf.getTermino()));
            colunas.add(Uteis.DiffTempo.DiferencaTempo(bf.getCaptura().getDataAtual(), bf.getTermino()) );

            linhasArquivadas.add(colunas);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoOndas;
    private javax.swing.JButton btnAtualizaOndasPadrao;
    private javax.swing.JButton btnCarregaOndas;
    private javax.swing.JButton btnFiltrar1;
    private javax.swing.JButton btnLimparFiltro;
    private javax.swing.JComboBox comboArquivadasEquip;
    private javax.swing.JComboBox comboConEquipamento;
    private javax.swing.JComboBox comboDataFim;
    private javax.swing.JComboBox comboDataIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtfArquivadasEquip;
    private javax.swing.JTextField jtfConEquipamento;
    private javax.swing.JPanel panelHarmonicas;
    private javax.swing.JPanel panelOnda;
    private javax.swing.JPanel panelPadraoHarmonicas;
    private javax.swing.JPanel panelPadraoOnda;
    private javax.swing.JCheckBox radioData;
    private javax.swing.JCheckBox radioEquip;
    private javax.swing.JPanel tabCadastro;
    private javax.swing.JPanel tabConsulta;
    private javax.swing.JTable tabelaArquivadas;
    private javax.swing.JTable tabelaOnLine;
    // End of variables declaration//GEN-END:variables

}
