/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPComparacao.java
 *
 * Created on Jun 14, 2012, 11:39:39 AM
 */
package Visualizacao;


import Graficos.CriaGrafico;
import Uteis.EncontraPadroes;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.CapturaAtual;
import modelo.OndaPadrao;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import persistencia.CapturaAtualDAO;
import persistencia.Conexao;

/**
 *
 * @author cliente
 * rewrite by rebonatto
 */
public class FormPComparacao extends javax.swing.JDialog {
    private static CapturaAtual bean;

    /** Creates new form FormPComparacao */
//    public FormPComparacao(java.awt.Frame parent, boolean modal, int tomTabela, int equipTabela,int codondaTabela, int codondaptabela, FormPSupervisao obj, int count) throws SQLException {
    public FormPComparacao(java.awt.Frame parent, boolean modal, CapturaAtual cap)  {
        super(parent, modal);
        bean = cap;
        initComponents();
        setTitle(" " + bean.getCodEquip().getDesc() + " " + bean.getCodEquip().getCodTipo().getDesc() + " " +bean.getCodEquip().getCodMarca().getDesc() + " " + bean.getCodEquip().getCodModelo().getDesc());        
        
        /* pega os dados da captura que veio e monta os graficos */
        // monta grafico de linhas
        JFreeChart chart = CriaGrafico.createChartLinhas(bean, true);
        ChartPanel crtPanelOnda = new ChartPanel(chart);
        crtPanelOnda.setPreferredSize(new java.awt.Dimension(500, 370));
        // monta grafico de barras
        ChartPanel crtPanelBarras = new ChartPanel(CriaGrafico.createChartBarras(bean, true, true));
        crtPanelBarras.setPreferredSize(new java.awt.Dimension(500, 370));
        
        OndaPadrao padrao = EncontraPadroes.minDifValorMedio(bean);
        
        if (bean.getCodTipoOnda().getCodTipoOnda() == 1){ // a captura é uma fase                    
            jpOndaFase.removeAll();
            jpOndaFase.add(crtPanelOnda);
            jpOndaFase.revalidate();
            jpOndaFase.repaint();                                                
        
            jpBarraFase.removeAll();
            jpBarraFase.add(crtPanelBarras);
            jpBarraFase.revalidate();
            jpBarraFase.repaint();
            
            jtfVmFaseAtual.setText(String.valueOf(bean.getValorMedio()));
            jtfEficazFaseAtual.setText(String.valueOf(bean.getEficaz()));
            jtfGainFaseAtual.setText(String.valueOf(bean.getGain()));
            jtfOffsetFaseAtual.setText(String.valueOf(bean.getOffset())); 
            if (padrao != null){
                jtfVmFasePadrao.setText(String.valueOf(padrao.getValorMedio()));
                jtfEficazFasePadrao.setText(String.valueOf(padrao.getEficaz()));
                jtfGainFasePadrao.setText(String.valueOf(padrao.getGain()));
                jtfOffsetFasePadrao.setText(String.valueOf(padrao.getOffset()));                 
            }
        }
        
        
        if (bean.getCodTipoOnda().getCodTipoOnda() == 2){ // a captura é uma fuga
            jpOndaFuga.removeAll();
            jpOndaFuga.add(crtPanelOnda);
            jpOndaFuga.revalidate();
            jpOndaFuga.repaint();                                                
        
            jpBarraFuga.removeAll();
            jpBarraFuga.add(crtPanelBarras);
            jpBarraFuga.revalidate();
            jpBarraFuga.repaint();
            
            jtfVmFugaAtual.setText(String.valueOf(bean.getValorMedio()));
            jtfEficazFugaAtual.setText(String.valueOf(bean.getEficaz()));
            jtfGainFugaAtual.setText(String.valueOf(bean.getGain()));
            jtfOffsetFugaAtual.setText(String.valueOf(bean.getOffset()));
            if (padrao != null){
                jtfVmFugaPadrao.setText(String.valueOf(padrao.getValorMedio()));
                jtfEficazFugaPadrao.setText(String.valueOf(padrao.getEficaz()));
                jtfGainFugaPadrao.setText(String.valueOf(padrao.getGain()));
        jtfOffsetFugaPadrao.setText(String.valueOf(padrao.getOffset()));                 
            }
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jtfVmFugaAtual = new javax.swing.JTextField();
        jtfEficazFugaAtual = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jtfGainFugaAtual = new javax.swing.JTextField();
        jtfOffsetFugaAtual = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jtfEficazFaseAtual = new javax.swing.JTextField();
        jtfGainFaseAtual = new javax.swing.JTextField();
        jtfOffsetFaseAtual = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jtfVmFaseAtual = new javax.swing.JTextField();
        jpOndaFuga = new javax.swing.JPanel();
        jpBarraFase = new javax.swing.JPanel();
        jpOndaFase = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jtfVmFasePadrao = new javax.swing.JTextField();
        jtfEficazFasePadrao = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jtfGainFasePadrao = new javax.swing.JTextField();
        jtfOffsetFasePadrao = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jtfVmFugaPadrao = new javax.swing.JTextField();
        jtfEficazFugaPadrao = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jtfGainFugaPadrao = new javax.swing.JTextField();
        jtfOffsetFugaPadrao = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jpBarraFuga = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Estatisticas Diferencial Atual"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setText("Valor Medio:");
        jPanel17.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, -1, -1));

        jtfVmFugaAtual.setEditable(false);
        jtfVmFugaAtual.setText(" ");
        jPanel17.add(jtfVmFugaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 67, 21));

        jtfEficazFugaAtual.setEditable(false);
        jtfEficazFugaAtual.setText(" ");
        jPanel17.add(jtfEficazFugaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 67, 21));

        jLabel67.setText("mA");
        jPanel17.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 20));

        jLabel68.setText("Valor Eficaz:");
        jPanel17.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel69.setText("Gain:");
        jPanel17.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jtfGainFugaAtual.setEditable(false);
        jtfGainFugaAtual.setText(" ");
        jPanel17.add(jtfGainFugaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 21));

        jtfOffsetFugaAtual.setEditable(false);
        jtfOffsetFugaAtual.setText(" ");
        jPanel17.add(jtfOffsetFugaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, 21));

        jLabel70.setText("Offset:");
        jPanel17.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, 110));

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Estatisticas Fase Atual"));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setText("Valor Eficaz:");
        jPanel18.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel47.setText("Gain:");
        jPanel18.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel48.setText("Offset:");
        jPanel18.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jtfEficazFaseAtual.setEditable(false);
        jtfEficazFaseAtual.setText(" ");
        jPanel18.add(jtfEficazFaseAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 67, 21));

        jtfGainFaseAtual.setEditable(false);
        jtfGainFaseAtual.setText(" ");
        jPanel18.add(jtfGainFaseAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 21));

        jtfOffsetFaseAtual.setEditable(false);
        jtfOffsetFaseAtual.setText(" ");
        jPanel18.add(jtfOffsetFaseAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, 21));

        jLabel49.setText("mA");
        jPanel18.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 20));

        jLabel50.setText("Valor Medio:");
        jPanel18.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, -1, -1));

        jtfVmFaseAtual.setEditable(false);
        jtfVmFaseAtual.setText(" ");
        jPanel18.add(jtfVmFaseAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 67, 21));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 214, 110));

        jpOndaFuga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpOndaFuga.setPreferredSize(new java.awt.Dimension(400, 530));
        jPanel1.add(jpOndaFuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 480, 370));

        jpBarraFase.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jpBarraFase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 480, 370));

        jpOndaFase.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpOndaFase.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.add(jpOndaFase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 480, 370));

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Estatisticas Fase Padrao"));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setText("Valor Medio:");
        jPanel19.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, -1, -1));

        jtfVmFasePadrao.setEditable(false);
        jtfVmFasePadrao.setText(" ");
        jPanel19.add(jtfVmFasePadrao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 67, 21));

        jtfEficazFasePadrao.setEditable(false);
        jtfEficazFasePadrao.setText(" ");
        jPanel19.add(jtfEficazFasePadrao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 67, 21));

        jLabel62.setText("mA");
        jPanel19.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 20));

        jLabel63.setText("Valor Eficaz:");
        jPanel19.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel64.setText("Gain:");
        jPanel19.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jtfGainFasePadrao.setEditable(false);
        jtfGainFasePadrao.setText(" ");
        jPanel19.add(jtfGainFasePadrao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 21));

        jtfOffsetFasePadrao.setEditable(false);
        jtfOffsetFasePadrao.setText(" ");
        jPanel19.add(jtfOffsetFasePadrao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, 21));

        jLabel65.setText("Offset:");
        jPanel19.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 12, -1, 110));

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Estatisticas Diferencial Padrao"));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setText("Valor Medio:");
        jPanel20.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, -1, -1));

        jtfVmFugaPadrao.setEditable(false);
        jtfVmFugaPadrao.setText(" ");
        jPanel20.add(jtfVmFugaPadrao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 67, 21));

        jtfEficazFugaPadrao.setEditable(false);
        jtfEficazFugaPadrao.setText(" ");
        jPanel20.add(jtfEficazFugaPadrao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 67, 21));

        jLabel72.setText("mA");
        jPanel20.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 20));

        jLabel73.setText("Valor Eficaz:");
        jPanel20.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel74.setText("Gain:");
        jPanel20.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jtfGainFugaPadrao.setEditable(false);
        jtfGainFugaPadrao.setText(" ");
        jPanel20.add(jtfGainFugaPadrao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 21));

        jtfOffsetFugaPadrao.setEditable(false);
        jtfOffsetFugaPadrao.setText(" ");
        jPanel20.add(jtfOffsetFugaPadrao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, 21));

        jLabel75.setText("Offset:");
        jPanel20.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 220, 110));

        jpBarraFuga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jpBarraFuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 480, 370));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            CapturaAtualDAO capdao = new CapturaAtualDAO();
            CapturaAtual bean = capdao.localiza(4975560);
            
            public void run() {
                FormPComparacao dialog = null;
                try {
                    dialog = new FormPComparacao(new javax.swing.JFrame(), true, bean);
                } catch (Exception ex) {
                    Logger.getLogger(FormPComparacao.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jpBarraFase;
    private javax.swing.JPanel jpBarraFuga;
    private javax.swing.JPanel jpOndaFase;
    private javax.swing.JPanel jpOndaFuga;
    private javax.swing.JTextField jtfEficazFaseAtual;
    private javax.swing.JTextField jtfEficazFasePadrao;
    private javax.swing.JTextField jtfEficazFugaAtual;
    private javax.swing.JTextField jtfEficazFugaPadrao;
    private javax.swing.JTextField jtfGainFaseAtual;
    private javax.swing.JTextField jtfGainFasePadrao;
    private javax.swing.JTextField jtfGainFugaAtual;
    private javax.swing.JTextField jtfGainFugaPadrao;
    private javax.swing.JTextField jtfOffsetFaseAtual;
    private javax.swing.JTextField jtfOffsetFasePadrao;
    private javax.swing.JTextField jtfOffsetFugaAtual;
    private javax.swing.JTextField jtfOffsetFugaPadrao;
    private javax.swing.JTextField jtfVmFaseAtual;
    private javax.swing.JTextField jtfVmFasePadrao;
    private javax.swing.JTextField jtfVmFugaAtual;
    private javax.swing.JTextField jtfVmFugaPadrao;
    // End of variables declaration//GEN-END:variables
}
